# Generated by Django 3.1.6 on 2023-10-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(verbose_name='date added')),
                ('due_date', models.DateTimeField(verbose_name='due date')),
                ('task_giver', models.CharField(max_length=30)),
                ('task_done_by', models.CharField(blank=True, max_length=30)),
                ('task_done_date', models.DateTimeField(blank=True, null=True, verbose_name='done date')),
            ],
        ),
    ]
