# Generated by Django 3.1.6 on 2023-10-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chore', models.CharField(max_length=30)),
                ('assigned_date', models.DateTimeField(verbose_name='date added')),
                ('due_date', models.DateTimeField(verbose_name='due date')),
                ('chore_assigner', models.CharField(max_length=30)),
                ('chore_done_by', models.CharField(blank=True, max_length=30)),
                ('chore_done_date', models.DateTimeField(blank=True, null=True, verbose_name='done date')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
