# Generated by Django 3.1.6 on 2023-10-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_auto_20231013_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='chore_priority',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
